name: test

on:
  pull_request:
    branches:
      - main
  #   paths:
  #   - 'environments/prod/values.prod.yaml'
  #   - 'environments/prod/saas-app-prod/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    # env:
    #   MAGDA_FQDN: prod-stable
    #   CLUSTER_ZONE: australia-southeast1

    name: Test job
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: "csv"
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: yarn install
        run: yarn install --frozen-lockfile
      - name: Run JS
        id: runJs
        run: node index.js
        env:
          DEV_MAGDA_API_ID: ${{ secrets.DEV_MAGDA_API_ID }}
          ADDED_FILES: "${{ steps.files.outputs.added }}"
          MODIFIED_FILES: "${{ steps.files.outputs.modified }}"
          # REMOVED_FILES: "${{ steps.files.outputs.removed }}"
          # RENAMED_FILES: "${{ steps.files.outputs.renamed }}"
